### ISSUE TITLE
Consider a way to report build version in tests

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/guide-kubernetes-microprofile-health#26]
The tests in this guide do not generate a console.log, thus the common way to report the build version in the tests does not work. Need to work out a way to report the build version in automated tests.

**Comment by proubatsis** [comment]
The logs from `console.log` are printed in travis when the `kubectl logs ...` command is run. You can see that the build version is printed in the travis build @evelinec 

https://travis-ci.org/OpenLiberty/guide-kubernetes-microprofile-health/jobs/464529592#L1549

> Launching defaultServer (Open Liberty 18.0.0.3/wlp-1.0.22.cl180320180905-2337) on IBM J9 VM, version 8.0.5.26 - pxa6480sr5fp26-20181115_03(SR5 FP26) (en_US)

**Comment by gkwan-ibm** [comment]
close:
-  the `kubectl logs` in the travisTest.sh can show the build versions
