### ISSUE TITLE
Build fail - The job exceeded the maximum log length

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/guide-kubernetes-microprofile-health#28]
https://travis-ci.org/OpenLiberty/guide-kubernetes-microprofile-health/builds/464278979?utm_medium=notification&utm_source=email

The job exceeded the maximum log length, and has been terminated.

To reduce the logs, try following in yaml
- mvn -B package
- wget --quiet ...

**Comment by gkwan-ibm** [comment]
as well as other kube guides

**Comment by proubatsis** [comment]
PRs Merged

**Comment by gkwan-ibm** [comment]
Look like `mvn -q...` not work
https://travis-ci.org/OpenLiberty/guide-kubernetes-microprofile-health/builds/464895467
