### ISSUE TITLE
Multipane Issues

### ISSUE THREAD

**Issue by andrewdes** [OpenLiberty/guide-kubernetes-microprofile-health#37]
**Prerequisites**
- [x] None of the links in the section open in a new tab

**Configuring readiness probes**
- [x] `initialDelaySeconds` hotspot only highlights one instance of it in the yaml file (it appears in multiple places). Same with `failureThreshold` and `periodSeconds`

**Comment by justineechen** [comment]
https://github.com/OpenLiberty/guides-common/pull/233/
