### ISSUE TITLE
Dev Mode verification

### ISSUE THREAD

**Issue by MaiHameed** [OpenLiberty/guide-kubernetes-microprofile-health#74]
Tested on a fresh installation of Ubuntu 18, on the `dev-mode` branch, with the guide on lgdev.

- [ ] the CLI tool `kubectl` does not come automatically installed with Minikube, would suggest adding a small sentence in the prerequisite section to acknowledge this. Same issue with the kube config guide.

- [x] The section of the guide that waits till the pods are ready after making them unhealthy does not have updated timestamps to show that time has passed. The guide mentions time passing yet the age is still 6m. See below: 
![image](https://user-images.githubusercontent.com/26514093/71931785-9092f300-316c-11ea-8ac1-e13e4f4fc91c.png)

**Comment by NimG98** [comment]
> * [ ]  the CLI tool `kubectl` does not come automatically installed with Minikube, would suggest adding a small sentence in the prerequisite section to acknowledge this. Same issue with the kube config guide.

Could you please make the issue in the guides-common repo? Since that section is part of the 
`kube-prereq.adoc` file, which affects multiple kubernetes guides
