### ISSUE TITLE
peer review (macOS)

### ISSUE THREAD

**Issue by jimmy1wu** [OpenLiberty/guide-kubernetes-microprofile-health#75]
**Changing the ready state of the system microservice**
- [x] In this section there are two outputs provided after it prompts us to enter the command `kubectl get pods`. Is the first one (where everything is ready) supposed to be there? We already checked that all the pods were ready in `Deploying the microservices`.
<kbd>
<img width="570" alt="Screen Shot 2020-01-08 at 12 09 45 PM" src="https://user-images.githubusercontent.com/33457590/71999638-c937d880-320f-11ea-9b95-3857f1b9b7bf.png">
</kbd>

- [x] The wording says both system pods, but only one system pod is ready in the sample output
<kbd>
<img width="556" alt="Screen Shot 2020-01-08 at 12 13 28 PM" src="https://user-images.githubusercontent.com/33457590/72000059-7c083680-3210-11ea-825b-7299b426cc61.png">
</kbd>

**Comment by NimG98** [comment]
> - [ ] The wording says both system pods, but only one system pod is ready in the sample output
> <kbd>
> <img width="556" alt="Screen Shot 2020-01-08 at 12 13 28 PM" src="https://user-images.githubusercontent.com/33457590/72000059-7c083680-3210-11ea-825b-7299b426cc61.png">
> </kbd>

- It tries to show `1/1` for one of the system pods instead if both because they are trying to show it porgressively one-by-one each system pod becoming ready, as mentioned by:
    > will start to become healthy again
